### ISSUE TITLE
the question about TE quantification

### ISSUE THREAD

**Issue by songlyzz** [juheon/LRCAGE#1]
Hi juheon,
 I have read your recent published paper "Epigenetic therapy potentiates transposable element transcription to create tumor-enriched antigens in glioblastoma cells", it is really solid results for TE specific antigens for tumor.
 There I have some questions:
>
![1726149113969](https://github.com/user-attachments/assets/c85a422f-3ab8-49be-9e60-2bfee53814bd)

I noticed that you normalized the TE for gene's expression, but you do not mention the gene's expression whether normalized for TE. In my opinion, they should nomalize separately.
Meanwhile, I did not see the reference of TE's locus refered, I am curious about how many reference TE contain.

Yours sincerely.

**Comment by juheon** [comment]
Hello,

For TE annotation, we utilized Repeatmasker from the UCSC Table Browser for the hg38 genome assembly.
